services:
  postgis_db:
    build: ../container-postgis/
    restart: unless-stopped
    container_name: postgis
    hostname: postgis
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
  dashboard:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@my.domain
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "80:80"
  app:
    build: /container-python-scripts/
    container_name: python_scripts
    image: my-python-scripts
    depends_on:
      - postgis_db
    ports:
      - "8081:3000"
