package models

import org.locationtech.jts.geom.Geometry

case class LineAndPolyRecordDTO(osm_id: String,
                                access: String,
                                amenity: String,
                                area: String,
                                barrier: String,
                                bicycle: String,
                                brand: String,
                                bridge: String,
                                boundary: String,
                                buildings: String,
                                culvert: String,
                                embankment: String,
                                foot: String,
                                harbour: String,
                                highway: String,
                                landuse: String,
                                leisure: String,
                                lock: String,
                                name: String,
                                natural: String,
                                place: String,
                                surface: String,
                                tourism: String,
                                tracktype: String,
                                watermark: String,
                                waterway: String,
                                wetland: String,
                                wood: String,
                                tags: String,
                                geometry: Geometry)
